run:
  timeout: 5m
  modules-download-mode: readonly
output:
  sort-results: true
linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: github.com/satori/go.uuid
            desc: Use github.com/google/uuid or github.com/gofrs/uuid instead
  errcheck:
    check-type-assertions: true
    check-blank: true
    ignore: ""
    exclude-functions:
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - (fmt.State).Write
      - (*bufio.Writer).WriteByte
      - (*bufio.Writer).WriteRune
      - (*bufio.Writer).WriteString
      - (*github.com/richardwilkes/toolbox/xio.ByteBuffer).Insert
      - (*github.com/richardwilkes/toolbox/xio.ByteBuffer).InsertByte
      - (*github.com/richardwilkes/toolbox/xio.ByteBuffer).InsertRune
      - (*github.com/richardwilkes/toolbox/xio.ByteBuffer).InsertString
      - (*github.com/richardwilkes/toolbox/xio.ByteBuffer).Write
      - (*github.com/richardwilkes/toolbox/xio.ByteBuffer).WriteByte
      - (*github.com/richardwilkes/toolbox/xio.ByteBuffer).WriteRune
      - (*github.com/richardwilkes/toolbox/xio.ByteBuffer).WriteString
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - opinionated
      - experimental
    disabled-checks:
      - sloppyReassign
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    settings:
      printf:
        funcs:
          - Errorf
          - Warnf
          - Infof
          - Debugf
          - Fatalf
          - StartRootSpanf
          - StartSubSpanf
          - EndWithMsgf
          - Newf
          - NewWithCausef
  misspell:
    locale: US
  staticcheck:
    checks: ["all", "-SA3000", "-SA5008"]
  gosec:
    excludes:
      - G104
      - G110
      - G204
      - G301
      - G304
      - G306
      - G601
linters:
  disable-all: true
  enable:
    - depguard
    - errcheck
    - errorlint
    - exportloopref
    - goconst
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - noctx
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
issues:
  exclude-use-default: false
  exclude:
    - "fieldalignment: struct with \\d+ pointer bytes could be"
    - "package-comments: should have a package comment"
    - "stdmethods: method MarshalJSON"
    - "stdmethods: method UnmarshalJSON"
