version: '2'
run:
  modules-download-mode: readonly
  tests: true
linters:
  default: none
  enable:
    - copyloopvar
    - depguard
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/satori/go.uuid
              desc: Use github.com/google/uuid or github.com/gofrs/uuid instead
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - encoding/binary.Write
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (fmt.State).Write
        - (*bufio.Writer).WriteByte
        - (*bufio.Writer).WriteRune
        - (*bufio.Writer).WriteString
        - (*github.com/richardwilkes/toolbox/v2/xterm.AnsiWriter).Write
        - (*github.com/richardwilkes/toolbox/v2/xterm.AnsiWriter).WriteByte
        - (*github.com/richardwilkes/toolbox/v2/xterm.AnsiWriter).WriteString
        - (*github.com/richardwilkes/toolbox/v2/xbytes.InsertBuffer).Insert
        - (*github.com/richardwilkes/toolbox/v2/xbytes.InsertBuffer).InsertByte
        - (*github.com/richardwilkes/toolbox/v2/xbytes.InsertBuffer).InsertRune
        - (*github.com/richardwilkes/toolbox/v2/xbytes.InsertBuffer).InsertString
        - (*github.com/richardwilkes/toolbox/v2/xbytes.InsertBuffer).Write
        - (*github.com/richardwilkes/toolbox/v2/xbytes.InsertBuffer).WriteByte
        - (*github.com/richardwilkes/toolbox/v2/xbytes.InsertBuffer).WriteRune
        - (*github.com/richardwilkes/toolbox/v2/xbytes.InsertBuffer).WriteString
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - sloppyReassign
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gosec:
      excludes:
        - G103
        - G104
        - G110
        - G115
        - G204
        - G301
        - G302
        - G303
        - G304
        - G306
        - G307
        - G601
        - G602
    govet:
      disable:
        - composites
      enable-all: true
      settings:
        printf:
          funcs:
            - Errorf
            - Warnf
            - Infof
            - Debugf
            - Fatalf
            - StartRootSpanf
            - StartSubSpanf
            - EndWithMsgf
            - Newf
            - NewWithCausef
        shadow:
          strict: true
    misspell:
      locale: US
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    revive:
      rules:
        - name: blank-imports
          disabled: false
        - name: context-as-argument
          disabled: false
        - name: context-keys-type
          disabled: false
        - name: dot-imports
          disabled: false
        - name: error-return
          disabled: false
        - name: error-strings
          disabled: false
        - name: error-naming
          disabled: false
        - name: exported
          disabled: false
        - name: if-return
          disabled: false
        - name: increment-decrement
          disabled: false
        - name: var-naming
          disabled: false
        - name: var-declaration
          disabled: false
        - name: package-comments
          disabled: true
        - name: range
          disabled: false
        - name: receiver-naming
          disabled: false
        - name: time-naming
          disabled: false
        - name: unexported-return
          disabled: false
        - name: indent-error-flow
          disabled: false
        - name: errorf
          disabled: false
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          disabled: false
    staticcheck:
      checks:
        - all
        - -ST1000
        - -SA3000
        - -SA5008
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: 'fieldalignment: struct with \d+ pointer bytes could be'
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
