#!/bin/bash
set -e

echo Building module gnu.trove...
cd ../gnu.trove
./build

echo Building module org.apache.commons.logging...
cd ../org.apache.commons.logging
./build

echo Building module org.apache.fontbox...
cd ../org.apache.fontbox
./build

echo Building module org.apache.pdfbox...
cd ../org.apache.pdfbox
./build

echo Building module com.lowagie.text...
cd ../com.lowagie.text
./build

echo Building module com.trollworks.toolkit...
cd ../toolkit
./build
