#!/bin/bash

APP_VERSION=4.11

PKG_BASE=pkg
DISK_ROOT="$PKG_BASE/GURPS Character Sheet $APP_VERSION"
APP_ROOT="$DISK_ROOT/GURPS Character Sheet"
PKG_TMP=$PKG_BASE/tmp
DISK_IMAGE=gcs-$APP_VERSION-mac.dmg

./build-deps

echo Building module com.trollworks.gcs...
./build

echo Packaging GURPS Character Sheet...

/bin/rm -rf $PKG_BASE
mkdir -p "$APP_ROOT"
mkdir -p $PKG_TMP/package/macosx

java --module-path ../java_modules --module com.trollworks.gcs/com.trollworks.gcs.app.GCSImages -icns -dir $PKG_TMP
java --module-path ../java_modules --module com.trollworks.gcs/com.trollworks.gcs.app.GCSInfoPlistCreator $PKG_TMP/package/macosx

javapackager -deploy -native image --module-path ../java_modules --module com.trollworks.gcs -nosign -outdir "$APP_ROOT" -name gcs -BappVersion=$APP_VERSION -Bidentifier=com.trollworks.gcs -BdropinResourcesRoot=$PKG_TMP

mv $PKG_TMP/*.icns "$APP_ROOT/gcs.app/Contents/Resources/"
mv $PKG_TMP/package/macosx/PkgInfo "$APP_ROOT/gcs.app/Contents/"
mv "$APP_ROOT/gcs.app" "$APP_ROOT/GURPS Character Sheet.app"

/bin/cp -R ../gcs_library/Library "$APP_ROOT/"
ln -s /Applications "$APP_ROOT/../Applications"

echo Creating disk image...
/bin/rm -f $DISK_IMAGE
ACTUAL_SIZE=`/usr/bin/du -sm "$DISK_ROOT" | sed -e 's/	.*//g'`
DISK_IMAGE_SIZE=$(expr $ACTUAL_SIZE + 20)
hdiutil create -srcfolder "$DISK_ROOT" -fs HFS+ -fsargs "-c c=64,a=16,e=16" -megabytes ${DISK_IMAGE_SIZE} -imagekey zlib-level=9 $DISK_IMAGE

/bin/rm -rf $PKG_BASE
