// Copyright (c) 1998-2026 by Richard A. Wilkes. All rights reserved.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, version 2.0. If a copy of the MPL was not distributed with
// this file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// This Source Code Form is "Incompatible With Secondary Licenses", as
// defined by the Mozilla Public License, version 2.0.

package nameable

import (
	"strings"
)

// Filler defines the method for filling the nameable key map.
type Filler interface {
	// FillWithNameableKeys fills the map with nameable keys.
	FillWithNameableKeys(m, existing map[string]string)
}

// Accesser defines the method for retrieving the nameable replacements.
type Accesser interface {
	// NameableReplacements returns the replacements to be used with Nameables.
	NameableReplacements() map[string]string
}

// Applier defines methods types that want to participate the nameable adjustments should implement.
type Applier interface {
	Accesser
	Filler
	// ApplyNameableKeys applies the nameable keys to this object.
	ApplyNameableKeys(m map[string]string)
}

// Extract nameable markers from the provided strings
// Each extracted marker will be a key and it's value will come from existing or be the default for the marker.
func Extract(target, existing map[string]string, in ...string) map[string]string {
	if target == nil {
		target = make(map[string]string)
	}
	for _, src := range in {
		for _, part := range ExtractParts(src, MarkerDelimiter, MarkerDelimiter) {
			if part.Placeholder {
				// Unescape any escaped marker delimiters and trim leading/trailing space
				raw := strings.TrimSpace(UnescapeRunes(part.Value, MarkerDelimiter))
				// Parse the marker text into a Marker
				if m, ok := NewMarker(raw); ok {
					// We may end up with duplicates and that's fine, they will collapse to one entry
					if v, exists := existing[m.Key()]; exists {
						target[m.Key()] = v
					} else {
						target[m.Key()] = m.DefaultValue()
					}
				}
			}
		}
	}
	return target
}

// Apply replaces nameable markers with their replacement values in a single string.
//
// Any unresolved markers are rendered in their compact form, "`@Label@`".
// The '@' wrapper is kept on unresolved markers so displayed text (sheet rows, table columns, tooltips) still
// visibly flags the value as an unresolved nameable marker.
func Apply(str string, replacements map[string]string) string {
	return ApplyToList([]string{str}, replacements)[0]
}

// ApplyToList replaces nameable markers with their replacement values in a slice of strings.
//
// Any unresolved markers are rendered in their compact form, "`@Label@`".
// The '@' wrapper is kept on unresolved markers so displayed text (sheet rows, table columns, tooltips) still
// visibly flags the value as an unresolved nameable marker.
func ApplyToList(in []string, replacements map[string]string) []string {
	if len(in) == 0 {
		return nil
	}

	// Process replacements so that keys are properly normalized
	nr := make(map[string]string, len(replacements))
	for k, v := range replacements {
		if m, ok := NewMarker(k); ok {
			// Use the normalized key value - this makes sure the replacement key uses the most recent normalization
			nr[m.Key()] = v
		} else {
			// Retain any malformed keys we were unable to normalize
			nr[k] = v
		}
	}

	out := make([]string, len(in))

	for i, str := range in {
		if !strings.ContainsRune(str, MarkerDelimiter) {
			// Skip processing a string with no markers
			out[i] = str
			continue
		}

		// Allocate a string builder to collect the processed string as we go
		var sb strings.Builder

		for _, part := range ExtractParts(str, MarkerDelimiter, MarkerDelimiter) {
			if part.Placeholder {
				// Unescape any escaped marker delimiters and trim leading/trailing space
				raw := strings.TrimSpace(UnescapeRunes(part.Value, MarkerDelimiter))

				// Parse the marker text into a Marker
				if m, ok := NewMarker(raw); ok {
					if r, hasReplacement := nr[m.Key()]; hasReplacement {
						sb.WriteString(r)
					} else {
						sb.WriteRune(MarkerDelimiter)
						sb.WriteString(m.Label) // We do not escape markers here by design
						sb.WriteRune(MarkerDelimiter)
					}
				} else {
					// Since marker parsing failed we write the exact marker back out, with delimiters
					sb.WriteRune(MarkerDelimiter)
					sb.WriteString(part.Value)
					sb.WriteRune(MarkerDelimiter)
				}
			} else {
				sb.WriteString(part.Value)
			}
		}
		out[i] = sb.String()
	}

	return out
}

// Reduce returns a map of the replacements which exist in nameables.
//
// The nameables map uses normalized keys due to being generated by Extract.
// The replacements map will have the keys normalized for comparison.
// The returned map will have normalized keys.
func Reduce(nameables, replacements map[string]string) map[string]string {
	// We can return early if there are no known namables
	if len(nameables) == 0 {
		return nil
	}

	ret := make(map[string]string, min(len(nameables), len(replacements)))
	for k, v := range replacements {
		key := k
		if m, ok := NewMarker(k); ok {
			// Use the normalized key value - this makes sure the replacement key uses the most recent normalization
			key = m.Key()
		}
		if _, ok := nameables[key]; ok {
			ret[k] = v
		}
	}

	return ret
}
