#! /usr/bin/env bash
set -eo pipefail

# Determine the directory this script is in.
# Can't use readlink -f, as -f isn't understood on macOS.
SCRIPT="$0"
while true; do
    RESOLVED="$(readlink "$SCRIPT" || true)"
    if [ -z $RESOLVED ]; then
        break;
    fi
    SCRIPT="$RESOLVED"
done
pushd "$(dirname "$SCRIPT")" >/dev/null
BASEDIR="$(pwd -P)"
popd >/dev/null

"$BASEDIR/support/bin/gcs" "-Xdock:icon=$BASEDIR/../Resources/app.png" -m com.trollworks.gcs/com.trollworks.gcs.app.GCS $@
